#!/usr/bin/env python3
"""
Test driver for OAI NRF implementation.
Handles test cases in the format generated by generate_test_cases.py.
"""
import json
import sys
import time
import uuid
import httpx
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional, Any, Tuple
from urllib.parse import urlparse

# Set default timeout for all HTTP requests (30 seconds for all phases)
DEFAULT_TIMEOUT = httpx.Timeout(30.0, connect=30.0, read=30.0, write=30.0, pool=30.0)


def build_full_url(resource_url: str, base_url: str) -> str:
    """Build a full URL from a resource URL and base URL."""
    if resource_url.startswith('/nnrf-nfm/v1'):
        parsed_base = urlparse(base_url)
        return f"{parsed_base.scheme}://{parsed_base.netloc}{resource_url}"
    elif resource_url.startswith('/'):
        return base_url.rstrip('/') + resource_url
    else:
        return base_url.rstrip('/') + '/' + resource_url


def replace_nf_instance_id_in_url(resource_url: str, new_instance_id: str) -> str:
    """Replace the NF instance ID in a resource URL with a new one."""
    if '/nf-instances/' not in resource_url:
        return resource_url
    
    parts = resource_url.split('/nf-instances/')
    if len(parts) == 2:
        suffix = parts[1].split('/', 1)[1] if '/' in parts[1] else ''
        if suffix:
            return f"{parts[0]}/nf-instances/{new_instance_id}/{suffix}"
        else:
            return f"{parts[0]}/nf-instances/{new_instance_id}"
    return resource_url


def execute_driving_state(
    driving_state: Optional[Dict[str, Any]], 
    base_url: str, 
    headers: Dict[str, str],
    client: httpx.Client
) -> Tuple[Optional[str], Optional[str]]:
    """Execute the driving state request and return (subscription_data, oauth_token) tuple."""
    if not driving_state:
        return None, None
    
    resource_url = driving_state.get('resource_url', '')
    method = driving_state.get('method', 'GET').upper()
    request_body = driving_state.get('request_body', {})
    driving_headers = {**headers, **driving_state.get('headers', {})}
    
    is_nf_registration = method == 'PUT' and '/nf-instances/' in resource_url and request_body
    
    if is_nf_registration:
        fresh_nf_id = str(uuid.uuid4())
        request_body = request_body.copy()
        request_body["nfInstanceId"] = fresh_nf_id
        resource_url = replace_nf_instance_id_in_url(resource_url, fresh_nf_id)
    
    full_url = build_full_url(resource_url, base_url)
    subscription_data = None
    oauth_token = None
    
    try:
        if method == 'PUT':
            response = client.put(full_url, headers=driving_headers, json=request_body if request_body is not None else None, timeout=DEFAULT_TIMEOUT)
        elif method == 'POST':
            response = client.post(full_url, headers=driving_headers, json=request_body if request_body is not None else None, timeout=DEFAULT_TIMEOUT)
        elif method == 'GET':
            response = client.get(full_url, headers=driving_headers, timeout=DEFAULT_TIMEOUT)
        elif method == 'DELETE':
            response = client.delete(full_url, headers=driving_headers, timeout=DEFAULT_TIMEOUT)
        else:
            return None, None
        
        if response.status_code in [200, 201, 204]:
            location = response.headers.get('Location', '')
            if location and 'subscriptions' in location:
                subscription_id = location.split('subscriptions/')[-1].split('/')[0]
                subscription_data = subscription_id
            
            if not subscription_data:
                try:
                    body = response.json()
                    if 'subscriptionId' in body:
                        subscription_data = body['subscriptionId']
                except (json.JSONDecodeError, KeyError):
                    pass
        
        return subscription_data, oauth_token
    except httpx.TimeoutException as e:
        print(f"  [DEBUG] Timeout in execute_driving_state: {method} {resource_url} - {str(e)}")
        return None, oauth_token
    except httpx.RequestError as e:
        print(f"  [DEBUG] Request error in execute_driving_state: {method} {resource_url} - {str(e)}")
        return None, oauth_token


def execute_test_request(
    request: Dict[str, Any], 
    base_url: str, 
    headers: Dict[str, str], 
    client: httpx.Client,
    driving_state_data: Optional[str] = None
) -> Dict[str, Any]:
    """Execute the actual test request and return the response details."""
    resource_url = request.get('resource_url', '')
    method = request.get('method', 'GET').upper()
    request_body = request.get('request_body', {})
    test_headers = {**headers, **request.get('headers', {})}
    
    if driving_state_data and '{subscriptionId}' in resource_url:
        resource_url = resource_url.replace('{subscriptionId}', driving_state_data)
    elif driving_state_data and 'subscriptions' in resource_url and '{subscriptionId}' not in resource_url:
        if resource_url.endswith('/subscriptions'):
            resource_url = f"{resource_url}/{driving_state_data}"
    
    full_url = build_full_url(resource_url, base_url)
    
    try:
        if method == 'PUT':
            response = client.put(full_url, headers=test_headers, json=request_body if request_body is not None else None, timeout=DEFAULT_TIMEOUT)
        elif method == 'POST':
            response = client.post(full_url, headers=test_headers, json=request_body if request_body is not None else None, timeout=DEFAULT_TIMEOUT)
        elif method == 'GET':
            response = client.get(full_url, headers=test_headers, timeout=DEFAULT_TIMEOUT)
        elif method == 'DELETE':
            response = client.delete(full_url, headers=test_headers, timeout=DEFAULT_TIMEOUT)
        else:
            return {
                "status_code": None,
                "status_message": f"Unsupported method: {method}",
                "response_body": None,
                "error": f"Unsupported HTTP method: {method}"
            }
        
        return {
            "status_code": response.status_code,
            "status_message": response.reason_phrase if hasattr(response, 'reason_phrase') else "",
            "response_body": response.text if response.text else None,
            "response_headers": dict(response.headers),
            "response_time": response.elapsed.total_seconds() if hasattr(response, 'elapsed') else None
        }
    except httpx.TimeoutException as e:
        print(f"  [DEBUG] Timeout in execute_test_request: {method} {resource_url} - {str(e)}")
        return {
            "status_code": None,
            "status_message": str(e),
            "response_body": None,
            "error": f"Timeout: {str(e)}",
            "error_type": "TimeoutException",
            "error_location": f"{method} {resource_url}"
        }
    except httpx.RequestError as e:
        print(f"  [DEBUG] Request error in execute_test_request: {method} {resource_url} - {str(e)}")
        return {
            "status_code": None,
            "status_message": str(e),
            "response_body": None,
            "error": str(e),
            "error_type": e.__class__.__name__,
            "error_location": f"{method} {resource_url}"
        }


def run_nrf_tests(
    test_cases_file: str, 
    base_url: str = "http://localhost:8080/nnrf-nfm/v1"
) -> str:
    """Run test cases against the OAI NRF and return the results file path."""
    try:
        with open(test_cases_file, 'r', encoding='utf-8') as f:
            test_cases = json.load(f)
    except json.JSONDecodeError as e:
        print(f"Error parsing JSON file: {e}")
        sys.exit(1)
    except FileNotFoundError:
        print(f"File not found: {test_cases_file}")
        sys.exit(1)
    
    if not isinstance(test_cases, list):
        print(f"Error: Test cases file must contain a JSON array")
        sys.exit(1)
    
    test_file_path = Path(test_cases_file)
    operation_name = test_file_path.stem.replace('_tests', '')
    
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    script_dir = Path(__file__).resolve().parent.parent
    results_dir = script_dir / "data" / "results"
    results_dir.mkdir(parents=True, exist_ok=True)
    results_file = str(results_dir / f"nrf_test_results_oai_{operation_name}_{timestamp}.json")
    
    results = []
    headers = {"Content-Type": "application/json"}
    total_cases = len(test_cases)
    
    # Process test cases
    for i, test_case in enumerate(test_cases, 1):
        
        test_name = test_case.get('name', f'Test case {i}')
        violated_constraints = test_case.get('violated_constraints', [])
        constraint_text = violated_constraints[0] if violated_constraints else "Unknown constraint"
        
        print(f"\n[{i}/{total_cases}] {test_name}")
        print(f"  Constraint: {constraint_text[:80]}...")
        
        # Create new client for each test case
        with httpx.Client(http1=False, http2=True, timeout=DEFAULT_TIMEOUT) as client:
            test_headers = {"Content-Type": "application/json"}
            
            # Execute driving state if present
            driving_state = test_case.get('driving_state')
            driving_state_data = None
            driving_state_error = None
            
            if driving_state:
                try:
                    driving_state_data, oauth_token = execute_driving_state(driving_state, base_url, test_headers, client)
                    if oauth_token:
                        test_headers["Authorization"] = f"Bearer {oauth_token}"
                except Exception as e:
                    driving_state_error = f"Exception in execute_driving_state: {str(e)}"
                    print(f"  [DEBUG] {driving_state_error}")
            
            # Execute test request
            request = test_case.get('request', {})
            if not request:
                result = {
                    "test_case_index": i - 1,
                    "test_name": test_name,
                    "operation": operation_name,
                    "constraint": constraint_text,
                    "status_code": None,
                    "status_message": "No request found in test case",
                    "response_body": None,
                    "error": "Test case missing request field"
                }
                results.append(result)
                continue
            
            response = execute_test_request(request, base_url, test_headers, client, driving_state_data)
            
            status_code = response.get("status_code")
            status_message = response.get("status_message", "")
            if status_code:
                print(f"  Status: {status_code} {status_message}")
            else:
                error = response.get("error", "Unknown error")
                print(f"  Error: {error}")
            
            result = {
                "test_case_index": i - 1,
                "test_name": test_name,
                "operation": operation_name,
                "constraint": constraint_text,
                "status_code": status_code,
                "status_message": status_message,
                "response_body": response.get("response_body"),
                "response_headers": response.get("response_headers"),
                "response_time": response.get("response_time"),
                "error": response.get("error"),
                "error_type": response.get("error_type"),
                "error_location": response.get("error_location"),
                "debug_info": {
                    "driving_state_error": driving_state_error
                }
            }
            results.append(result)
            
            # Small delay between requests
            time.sleep(0.1)
    
    # Save results
    with open(results_file, 'w', encoding='utf-8') as f:
        json.dump(results, f, indent=2, ensure_ascii=False)
    
    print(f"\n[✓] Test complete. Results saved to {results_file}")
    
    return results_file


def main() -> None:
    """Main entry point for the test driver."""
    if len(sys.argv) < 2:
        print("Usage: python test_oai.py <test_cases_file> [base_url]")
        print("  test_cases_file: Path to JSON file containing test cases (e.g., data/generated/NFStatusSubscribe_tests.json)")
        print("  base_url: Optional base URL for NRF (default: http://localhost:8080/nnrf-nfm/v1)")
        sys.exit(1)
    
    test_cases_file = sys.argv[1]
    base_url = sys.argv[2] if len(sys.argv) > 2 else "http://localhost:8080/nnrf-nfm/v1"
    
    run_nrf_tests(test_cases_file, base_url)


if __name__ == "__main__":
    main()
